# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
  
  .bar {
    fill: steelblue;
  }
  .bar:hover {
    fill: orange;
  }
  .tooltip {
    position: absolute;
    text-align: center;
    width: 60px;
    height: 28px;
    padding: 2px;
    font: 12px sans-serif;
    background: lightsteelblue;
    border: 0px;
    border-radius: 8px;
    pointer-events: none;
    opacity: 0;
  }
  .axis-label {
    font-size: 12px;
  }
  #chart {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 960px; /* Adjust to match the width of your chart */
  }
</style> 

<div id="chart"></div>
<div id="tooltip" class="tooltip"></div>

<!--
<div id="plot">
</div>
-->

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>
 
Welcome to our interactive exploration of Electric Vehicle (EV) trends in Washington State. This visualization tool is designed to offer you a comprehensive understanding of the EV market share in WA. As you navigate the page, you'll encounter a interactive elements—hover over the data points in our charts to reveal detailed information, such as specific numbers. Instruction is here to ensure an engaging and informative experience. Our goal is for you to leave with a deeper understanding of the key information driving EV adoption in WA.
